### PR TITLE
Added link to the Python varint implementation

### PR DESCRIPTION
**Pull request by uniconstructor**
Used this python package recently, works fine.

### CODE REVIEW

**Comment by rvagg** [comment]
@uniconstructor you used it for multiformats purposes? The code _looks_ right, but my Python eyes aren't very sharp so I may be missing subtleties.

**Comment by Stebalien** [comment]
_This_ unsigned varint spec specifies quite a few additional requirements (maximum encoded value, minimal encoding).

**Comment by BigLep** [comment]
Can someone else in the community verify that the linked python varint implementation conforms with multiformats/unsigned-varint ?  Core maintainers of IPLD/multiformats aren't Python experts.

**Comment by SgtPooki** [comment]
Took a quick look, but not a python expert, just a computer scientist. 

https://github.com/fmoo/python-varint/issues/9#issuecomment-1012454309 and issue thread show some examples of tests that could be modified to test further . However, based on that one comment (i did no validation of that statement's accuracy) and the "Unsigned LEB128" section at https://en.m.wikipedia.org/wiki/LEB128, it looks like there are a few conflicts:

- The signing of bits is backwards
    * instead of MSbit being 1 to indicate another byte, LEB128 does "Add high 1 bits on all but last (most significant) group to form bytes"
- LEB128: "allowing encoding of arbitrarily long numbers"
- 16384 decimal
    * this impl === 10000000 10000000 00000001 === 0x80 0x80 0x01
    * python-varint === 0x81 0x80 0x00

**Comment by rvagg** [comment]
thanks for looking @SgtPooki! based on that I'm going to close this, if someone wants to object to that analysis and relitigate this then we can re-open and reconsider cause it'd be great to add more implementations to the list

**Pull request closed without merging**
